CREATE OR REPLACE VIEW VW_WeatherLogs_PreviousWeekLogs
AS
SELECT
	*
FROM
	WeatherLogs
WHERE
	`Timestamp` >= FIRST_DAY_OF_WEEK(SUBDATE(CURDATE(), INTERVAL 7 DAY)) AND
	`Timestamp` < FIRST_DAY_OF_WEEK(CURDATE());